-- Kulturhuset Varde – seed-data. Kjør etter schema.sql.

insert into public.concerts (title, date, venue, description) values
  ('Jubileumskonsert', '2026-10-01', 'Sobra Scene', 'Mannskoret Varde inviterer til jubileumskonsert.'),
  ('Julekonsert', '2026-11-29', 'Borgund Kirke', 'Mannskoret Varde sammen med Ytre Suløens Jass-ensemble og Tricia Boutté.'),
  ('Festgudstjeneste', '2026-05-17', 'Ålesund Kirke', '');

insert into public.board_members (name, role, phone) values
  ('Einar Gundersen', 'Formann', '92 60 32 21'),
  ('Dag Frøysa', 'Nestformann', '98 20 74 56'),
  ('Sverre Petter Abelseth', 'Kasserer', '41 21 39 27'),
  ('Trond Inge Aarønes', 'Sekretær', '91 24 54 44'),
  ('Robert Valderhaug', 'Styremedlem', '91 31 59 40');

insert into public.sponsors (name) values
  ('Stiftelsen Kjell Holm'),
  ('Sparebanken Møre'),
  ('Hagenæs Shipping AS'),
  ('Brødrene Dahl AS'),
  ('Boligbyggern AS'),
  ('Bjørn Heggstad'),
  ('Dyrøy Betong AS'),
  ('Tafjord Kraft AS'),
  ('Dyrøy AS'),
  ('Mannskoret Varde – for betydelig dugnadsinnsats');

insert into public.members (name, voice, img) values
  ('Walter Stiegler', 'Dirigent', '/images/medlemmer/walter-stiegler.jpg'),
  ('Sverre Petter Abelseth', '1T', '/images/medlemmer/sverre-petter-abelseth.jpg'),
  ('Dag Frøysa', '1T', '/images/medlemmer/dag-froysa.jpg'),
  ('Magnus Jøssang', '1T', '/images/medlemmer/magnus-jossang.jpg'),
  ('Roy-Kasper Naalsund', '1T', '/images/medlemmer/roy-kasper-naalsund.jpg'),
  ('Ole Petter Velle', '1T', '/images/medlemmer/ole-petter-velle.jpg'),
  ('Bård Marthinsen', '1T', '/images/medlemmer/bard-marthinsen.jpg'),
  ('Håvard Storeide', '1T', '/images/medlemmer/havard-storeide.jpg'),
  ('Svein Skarbøvik', '1T', '/images/medlemmer/svein-skarbovik.jpg'),
  ('Oddvar Krogen', '2T', '/images/medlemmer/oddvar-krogen.jpg'),
  ('Einar Gundersen', '2T', '/images/medlemmer/einar-gundersen.jpg'),
  ('Ole Jørgen Rongved', '2T', '/images/medlemmer/ole-jorgen-rongved.jpg'),
  ('Tor Solvang', '2T', '/images/medlemmer/tor-solvang.jpg'),
  ('Geir Magnussen', '2T', '/images/medlemmer/geir-magnussen.jpg'),
  ('Bjørn Otto Godø', '2T', '/images/medlemmer/bjorn-otto-godo.jpg'),
  ('Bjørn Heggstad', '2T', '/images/medlemmer/bjorn-heggstad.jpg'),
  ('Oddvar Hessen', '2T', '/images/medlemmer/oddvar-hessen.jpg'),
  ('Terje Molnes', '2T', '/images/medlemmer/terje-molnes.jpg'),
  ('Håvard Lien', '2T', '/images/medlemmer/havard-lien.jpg'),
  ('Jan Erik Aarsæther', '2T', '/images/medlemmer/jan-erik-aarsaether.jpg'),
  ('Per Tore Langlo', '2T', '/images/medlemmer/per-tore-langlo.jpg'),
  ('Bjørnar Flem', '2T', '/images/medlemmer/bjornar-flem.jpg'),
  ('Knut Per Åkre', '2T', '/images/medlemmer/knut-per-akre.jpg'),
  ('Trond Inge Aarønes', '1B', '/images/medlemmer/trond-inge-aarones.jpg'),
  ('Robert Valderhaug', '1B', '/images/medlemmer/robert-valderhaug.jpg'),
  ('Finn Knudsen', '1B', '/images/medlemmer/finn-knudsen.jpg'),
  ('Jan Arne Hjertvik', '1B', '/images/medlemmer/jan-arne-hjertvik.jpg'),
  ('Roger Giske', '1B', '/images/medlemmer/roger-giske.jpg'),
  ('Roy Arne Sund', '1B', '/images/medlemmer/roy-arne-sund.jpg'),
  ('Petter Holstad', '1B', '/images/medlemmer/petter-holstad.jpg'),
  ('Knut Johan Muri', '1B', '/images/medlemmer/knut-johan-muri.jpg'),
  ('Jan Inge Sandvik', '1B', '/images/medlemmer/jan-inge-sandvik.jpg'),
  ('Einar Larsen', '1B', '/images/medlemmer/einar-larsen.jpg'),
  ('Jan-Erik Løken', '1B', '/images/medlemmer/jan-erik-loken.jpg'),
  ('Ole Urke', '1B', '/images/medlemmer/ole-urke.jpg'),
  ('Hans Petter Drønnen', '1B', '/images/medlemmer/hans-petter-dronnen.jpg'),
  ('Leif Ståle Søvik', '1B', '/images/medlemmer/leif-stale-sovik.jpg'),
  ('Bjørn Vinje', '2B', '/images/medlemmer/bjorn-vinje.jpg'),
  ('Per Gunnar Beyer', '2B', '/images/medlemmer/per-gunnar-beyer.jpg'),
  ('Inge Domaas', '2B', '/images/medlemmer/inge-domaas.jpg'),
  ('Stein Olav Kvalø', '2B', '/images/medlemmer/stein-olav-kvalo.jpg'),
  ('Stig Skaar', '2B', '/images/medlemmer/stig-skaar.jpg'),
  ('Malvin Dalhus', '2B', '/images/medlemmer/malvin-dalhus.jpg'),
  ('Arne Lie', '2B', '/images/medlemmer/arne-lie.jpg'),
  ('Bjarne Håvik', '2B', '/images/medlemmer/bjarne-havik.jpg'),
  ('Patrik Fugelsnes', '2B', '/images/medlemmer/patrik-fugelsnes.jpg'),
  ('Svein Kjøllesdal', '2B', '/images/medlemmer/svein-kjollesdal.jpg'),
  ('Ole Tommy Reite', '2B', '/images/medlemmer/ole-tommy-reite.jpg');
